name: Node.js and MongoDB Application

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js Dependencies
      run: |
        npm install

    - name: Lint with ESLint
      run: |
        npx eslint . --ext .js

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: tanmay238/knoteapp:latest

  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Modify Git Repository
      run: |
        git config user.email tanmay8928@gmail.com
        git config user.name Tanmay
        pwd
        cat deployment.yaml
        pwd
        sed -i "s+tanmay238/knoteapp.*+tanmay238/knoteapp:latest+g" deployment.yaml
        cat deployment.yaml
        git add .
        git commit -m 'Update image tag using GitHub Actions'
        git push origin main
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
